### ISSUE TITLE
cant close session foreach

### ISSUE THREAD

**Issue by wanglong9** [webfolderio/cdp4j#56]
```
List<SessionInfo> list = factory.list();
for (SessionInfo info : list) { 
  factory.close(info.getId());
}
```

it will throw errors like this

```
io.webfolder.cdp.exception.CdpException: java.net.ConnectException: Connection refused: connect
at io.webfolder.cdp.session.SessionFactory.list(SessionFactory.java:308)
at io.webfolder.cdp.session.SessionFactory.list(SessionFactory.java:289)
```

or

```
 2017-12-11 02:01:06.992 [main]  [ERROR]  cdp4j.factory {CdpSlf4jLogger.java:62} - java.io.FileNotFoundException: http://localhost:9222/json/close/e2d05a34-7617-4cde-8f55-30e97ee99522
 io.webfolder.cdp.exception.CdpException: java.io.FileNotFoundException: http://localhost:9222/json/close/e2d05a34-7617-4cde-8f55-30e97ee99522
	at io.webfolder.cdp.session.SessionFactory.close(SessionFactory.java:351)
	at io.webfolder.cdp.session.Session.close(Session.java:150)
	at io.webfolder.cdp.session.SessionFactory.close(SessionFactory.java:390)
	Caused by: java.io.FileNotFoundException: http://localhost:9222/json/close/e2d05a34-7617-4cde-8f55-30e97ee99522
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at io.webfolder.cdp.session.SessionFactory.close(SessionFactory.java:348)
	... 6 more
```

**Comment by wanglong9** [comment]
when i close session by step. it will throw exception like this

**Comment by wanglong9** [comment]
after create a new  LocalLaucher, can i use proxyIP to get SessionFactory

**Comment by prakapenka** [comment]
by the way, factory.close(...) does not closes headless sessions. 
Executing

```
ps -ef | grep chrome
``` 
founds some hanging headless sessions was not killed even when java process has stopped.

That seems to be a leak?

When opening one url one session is created. But if that page tries to open other tabs (like open more pages using target _blank) ends up in more then one sessions of headless browser exists.

I used to workaround it checking how many sessions was before I open some url and how many pages exists after I had open it.

**Comment by wanglong9** [comment]
i don‘’t use the headless sessions

**Comment by 2788** [comment]
@prakapenka  i think it's normal because The project use command "chrome --headless ..." start the chrome so i think the java program doesn't hold this chrome process. 
factory.close() It only close the sessions created by the java program which don't contain those session opened by click() or js.  You can read  [SessionFactory](https://github.com/webfolderio/cdp4j/blob/master/src/main/java/io/webfolder/cdp/session/SessionFactory.java) to find out how it work..

**Comment by wanglong9** [comment]
@2788 所有的session都是通过java程序启动的哦

**Comment by prakapenka** [comment]
@2788 for me it is totally not normal, but it is just my case and I am going to fork out away for my implementations.

Just if you interested why. 

Library exactly creates process of headless chrome when necessary. Let say I use this library in long running server and I need to re-start chrome time to time. For example I want to have clean home folder for next scenario. Let say I want to tweak chrome before every launch based on my input data. I can't or I have troubles to restart whole chrome process completely.

Another case is as I wrote above -click() or js can cause on a page running scripts (or just simple target=blank) that will open a dosen of new tabs (like do it advertisers) - so that I want to close all of these sessions (new tabs actually) before going forward - I can't. For long scenarios this amount of new session (opened tabs) grows very fast (let say I digging not so friendly sites) causing chrome out of memory or other side effects I am not going to have there.

Another scenario I want to use headless chrome launched completely independently from cdp library. In that case to connect to it I can call firstly http endpoint like 
```curl -s 127.0.0.1:<port>/json/list```
which returns for running chrome a list of possible sessions (actually ws endpoints for possible connect) - so I expect library to be able so start from this point to dig we have chrome+dev_tools there and then establish ws sessions which we want. I don't see this.

I would be happy one day SessionFactory will be able to do this. For me main idea factory should not distinguish sessions created by java or not created by java but just manage any session at the moment we have (at least we can discover) for running chrome instance with enabled dev-tools protocol.

**Comment by 2788** [comment]
@prakapenka I agree with you.  I think the session should hava a method which can record the open tabs by itself.
SessionFactory have a method list() which can list all the tabs and then you can use another method connect(sessionId) to connect what you want. You can read this method to what it do actually.

As for restart headless chrome ,  i don't know whether there is a method.
Gald  to discuss with you!

**Comment by 2788** [comment]
@wanglong9  我看了他的源码 发现他都是socket 控制chrome的，创建一个新的session 对应的方法里面写的就是 host:port/json/new 所有，java 退出 了但是你java程序里面没写关闭session也就是没有tab tab是一直存在的  可以通过host:port/json/list 查看

**Comment by webfolderio** [comment]
@prakapenka 

> For example I want to have clean home folder for next scenario.

You could create a new chrome profile for each startup.

Here is the sample: [MultiProcess.java](https://github.com/webfolderio/cdp4j/blob/master/src/test/java/io/webfolder/cdp/sample/MultiProcess.java)

**Comment by webfolderio** [comment]
@2788 

> SessionFactory have a method list() which can list all the tabs and then you can use another method connect(sessionId) to connect what you want. You can read this method to what it do actually.

This is a nice solution you can connect an existing session after intended or unintended restart.
